# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
