# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20180516_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='example',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
