# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedquiz',
            name='score',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
