# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180516_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
