# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingExercise', '0003_exercise_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
    ]
