# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codingExercise', '0005_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codingExercise.Chapter'),
        ),
    ]
