# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingExercise', '0006_exercise_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id']},
        ),
    ]
