# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingExercise', '0008_remove_exercise_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
